version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=NzgyNDk0NTI4OTY3MTQ3NTMy.X8NA0Q.cbGixjyVTPqwZssPTAdYIzLF2C4
      - GOOGLE_APPLICATION_CREDENTIALS=./key.json
      - DB_FILE=db/speecher.db
    volumes:
      - "./db:/workspace/db"
    