version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=
      - GOOGLE_APPLICATION_CREDENTIALS=./key.json
      - DB_FILE=db/speecher.db
    volumes:
      - "./db:/workspace/db"
    
